### ISSUE TITLE
Readme links to create new issues are 404'ing

### ISSUE THREAD

**Issue by igrigorik** [GoogleChrome/CrUX#1]
Ideally, we should have a template for creating new issues and feature requests. I believe GitHub has [supports](https://help.github.com/en/articles/creating-issue-templates-for-your-repository) for this?

**Comment by rviscomi** [comment]
Ah thanks, fixed the links. Leaving this issue open to create issue templates.

**Comment by rviscomi** [comment]
Created a [template for suggesting a new CrUX metric](https://github.com/GoogleChrome/CrUX/blob/master/.github/ISSUE_TEMPLATE/new-crux-metric-request.md). What info would you like to see in a bug report template?

**Comment by igrigorik** [comment]
New crux metric: lgtm. Bug: not sure! :) We can keep it free form and see if/what pops up.
