### ISSUE TITLE
Automatically Close Unused Tabs

### ISSUE THREAD

**Issue by KiaBoluki** [GoogleChrome/CrUX#11]
hi ;
This is an idea from a Chrome browser fan. 
I think it should be nice if Chrome browser automatically close unused tabs. The user can set it on or off and can set a timer for auto-close tabs. For example 10, 30 or 60 minutes, and useless or unseen tabs will automatically close after that time. Chrome browser uses RAM and CPU so if the user forgot to close old opened tabs their device maybe see slowness or other problems. 
The nominated tab for auto-closing should have these specs:

- It is not playing audio or video 
- It is not refreshing and its content is static
- It is not seen for a while

You can add a shortcut to reopen auto-closed tabs in the plus button right-click menu 
You can show a timer on tab for last 30 seconds and if the user opened that tab then the timer will reset.

I hope you find it noticeable and user friendly. 
Thank you. 
Good Luck.

**Comment by rviscomi** [comment]
Hi, if you have general feedback about the Chrome browser see https://support.google.com/chrome/answer/95315. This repo is about the Chrome UX Report, a dataset that measures user experiences. Closing this as off-topic.
