### ISSUE TITLE
Multiple Metrics in one Query

### ISSUE THREAD

**Issue by AlonaD** [GoogleChrome/CrUX#19]
When creating a query in the cloud for CrUX, I want to get results not only for one metric, like cls, or fcps, but for all of them. 
It is possible to do it. The expected result:
one query that requests all this metrics:
first_paint (FP)
first_contentful_paint (FCP)
dom_content_loaded (DCL)
onload (OL)
experimental.first_input_delay (FID)
(all that are listed in this article: [https://developer.chrome.com/blog/chrome-ux-report-bigquery/])
The metrics should be for a page, and the same for an origin.

Is there a way to do it, can you give me an example? Thank you

**Comment by tunetheweb** [comment]
Have a look at [this example SQL](https://github.com/GoogleChrome/CrUX/blob/main/sql/core-web-vitals.sql).

> The metrics should be for a page, and the same for an origin.

BigQuery only details data by Origin. Page-level data is only available via the API.
