### ISSUE TITLE
countries.json lists "bg" as Kosovo

### ISSUE THREAD

**Issue by zcorpan** [GoogleChrome/CrUX#27]
https://github.com/GoogleChrome/CrUX/blob/main/utils/countries.json#L163

Should this say Bulgaria instead? https://www.iso.org/obp/ui/#iso:code:3166:BG

**Comment by rviscomi** [comment]
Yes that looks like a bug. Thanks @zcorpan!

Luckily it doesn't look like this affects the `chrome-ux-report.experimental.GET_COUNTRY` function:

```sql
/* country_name: Bulgaria */
SELECT `chrome-ux-report.experimental.GET_COUNTRY`('bg') AS country_name
```
