### ISSUE TITLE
issue:the bottom left length of the tab can be minimised.

### ISSUE THREAD

**Issue by sahiladit** [GoogleChrome/CrUX#29]
**Proposal**
The bottom left length of the tab has extra length and does not merge with the address bar.

**Use cases**
It improves ui.

**screenshot**

<img width="110" alt="Screenshot 2024-03-17 at 8 42 20 PM" src="https://github.com/GoogleChrome/CrUX/assets/159920447/5e89d07e-4d7a-4e11-af9a-a43e69eab9ce">

**Comment by tunetheweb** [comment]
Please stop spamming issues. Reported to Github.

**Comment by sahiladit** [comment]
> Please stop spamming issues. Reported to Github.

Hey i didn't know this is a spam issue, i saw this and raised this.

**Comment by tunetheweb** [comment]
This does not appear to have anything to do with CrUX? Or the Chromium Dashboard when you raised https://github.com/GoogleChrome/chromium-dashboard/issues/3715 ?

For Chrome issues but please raise it at [crbug.com/new](https://crbug.com/new). Please also provide more details as to how you see this (what version of Chrome, what platform...etc.).

**Comment by sahiladit** [comment]
Thank you 👍🏻👍🏻
