### ISSUE TITLE
Google Chrome causes the modem to reboot

### ISSUE THREAD

**Issue by KostyaTretyak** [GoogleChrome/CrUX#8]
Sorry if I created this issue in the wrong repository, please pointing me to the correct one.

When I work with Google Chrome, there has been a problem with rebooting my modem (Verizon Netgear Jetpack AC791L) for the last month, maybe two. Reboots do not always happen, only under certain conditions:
1. this most often happened when I went to `https://drive.google.com/drive/u/0/my-drive` (Google Drive) and then opened one of some file (no matter which);
2. this also sometimes happens when I am on one of `youtube.com` pages;
3. the same thing sometimes happens when I just launch Google Chrome, which has 4 pinned tabs (translate.google.com, music.youtube.com, angular.io, material.angular.io).

As far as I understand, this happens when Chrome downloads information simultaneously in multiple streams.

At first I thought that the problem was in the modem itself, so I reset all the settings to factory settings, but the problem did not disappear. Then I turned off all Chrome extensions, but that didn't help either. I even install fresh Ubuntu 20.04 on my laptop (was Ubuntu 18.04), and then purchased a new Netgear Aircard AC815S modem. With the new modem, reboots became much less, but they still were.

Finally, when I start work with Mozilla Firefox (81.0 (64-bit)), I didn't see any modem reboots, even with the old modem. And at the same time, when I opened Google Chrome on the pages mentioned above, I was getting a reboot of the modem again.

I have:
- Google Chrome Version 86.0.4240.75 (Official Build) (64-bit)
- Ubuntu 20.04.1 LTS 64-bit (Memory 16 GB, Processor Intel® Core™ i5-7200U CPU @ 2.50GHz × 4)

**Comment by rviscomi** [comment]
Closing as off-topic to the CrUX dataset.

Please see https://support.google.com/chrome/answer/95315 if you have Chrome-specific feedback.
